### PR TITLE
Added Changing Gradient background for feature cards

### PR DESCRIPTION
**Pull request by Muz4mmil**
Now the **background of feature cards changes with feature**.
If you want to change the gradient color pair, you can do it by changing '`bgGradient`' property of features in `src/helpers/features.js`.
I have also changed the structure of `tailwind.configs.js` so that you can use your defined colors along with the default Tailwind colors.

### CODE REVIEW

**Comment by Muz4mmil** [comment]
Solves issue #1 fixed

**Comment by supunvindula** [comment]
Good work. Thanks

**Comment by Muz4mmil** [comment]
Hey @supunvindula 
I guess we missed something. or I created a new issue by mistake which got merged.
Because this one is not getting counted in hacktoberfest.
It says 'Not-Participating' in hacktoberfest page

Can you please try adding tags and labels of `hacktoberfest` and `hacktoberfest-accepted` to this issue?
Thanks

**Comment by Muz4mmil** [comment]
resolves #1 
closes #1

**Comment by supunvindula** [comment]
Hi @Muz4mmil check now. Refresh few times please

**Comment by Muz4mmil** [comment]
> Hi @Muz4mmil check now. Refresh few times please

Hey @supunvindula 
Thankyou so much for helping, the PR is getting counted and is in waiting now.
And Sorry for inconvenience, I'm new to open source and is still learning how stuff works.

**Comment by supunvindula** [comment]
Me too. No worries @Muz4mmil

**Pull request merged**
